#!/bin/bash
set -e

template=value="`cat tempalte`"

if [ $(id -u) -ne 0 ]; then 
  echo "Error: Please run as root"
  exit 1
fi

if [ -z ${name+x} ] || [ -z ${command+x} ]; then
	echo "Error: Please set name and command parameter"
	exit 1
fi
template="${template//<COMMAND>/$(printf %q "$command")}"

if [ -f "/etc/init.d/$name" ]; then
	echo "Error: Service '$name' already exists"
	exit 1
fi
template="${template//<NAME>/$name}"

if ! id -u "$username" &> /dev/null; then
	echo "Error: User '$username' not found"
	exit 1
fi
template="${template//<USER>/$user}"

template="${template//<DIRECTORY>/${directory:-.}}"
template="${template//<DESCRIPTION>/${description:-Starts '$name'-Service}}"
template="${template//<REQUIRED-START>/${required-start:-\$remote_fs \$syslog}}"
template="${template//<REQUIRED-STOP>/${required-stop:-\$remote_fs \$syslog}}"

#install
echo -e "$template" > "/etc/init.d/$name"
chmod +x "/etc/init.d/$name"
touch "/var/log/$name.log"
chown "$user" "/var/log/$name.log"
touch "/var/log/$name.err"
chown "$user" "/var/log/$name.err"
update-rc.d "$name" defaults
service "$name" start
